"""Haystack adapter generator."""

from typing import Dict, Any


def generate_haystack_adapter(quantizer_name: str, bit_width: int, dim: int) -> str:
    """Generate Haystack document store adapter code.

    Args:
        quantizer_name: Name of the quantizer.
        bit_width: Quantization bit width.
        dim: Vector dimensionality.

    Returns:
        Python code string for the adapter.
    """
    code = f'''"""
Haystack DocumentStore adapter using {quantizer_name} quantization.

Auto-generated by QuantVec-CLI.
"""

from typing import List, Optional, Dict, Any
import numpy as np

try:
    from haystack import Document
    from haystack.document_stores.types import DocumentStore
except ImportError:
    raise ImportError("Please install haystack: pip install quantvec-cli[haystack]")

from quantvec.quantizers import {quantizer_name.title().replace("quant", "Quant")}Quantizer


class QuantVecDocumentStore(DocumentStore):
    """A Haystack DocumentStore that uses {quantizer_name} quantization."""

    def __init__(
        self,
        dim: int = {dim},
        bit_width: int = {bit_width},
    ):
        self.dim = dim
        self.bit_width = bit_width
        self.quantizer = {quantizer_name.title().replace("quant", "Quant")}Quantizer(
            dim=dim, bit_width=bit_width
        )
        self._codes = None
        self._documents = []
        self._is_fitted = False

    def write_documents(self, documents: List[Document], policy: str = "fail") -> int:
        """Write documents to the store."""
        vectors = []
        for doc in documents:
            if doc.embedding is None:
                raise ValueError("Document must have embedding")
            vectors.append(doc.embedding)

        vectors = np.array(vectors, dtype=np.float32)

        if not self._is_fitted:
            self.quantizer.fit(vectors)
            self._is_fitted = True

        codes = self.quantizer.encode(vectors)

        if self._codes is None:
            self._codes = codes
        else:
            self._codes = self._merge_codes(self._codes, codes)

        self._documents.extend(documents)
        return len(documents)

    def search(
        self,
        query_embedding: List[float],
        top_k: int = 10,
        filters: Optional[Dict[str, Any]] = None,
    ) -> List[Document]:
        """Search for similar documents."""
        query_vec = np.array(query_embedding, dtype=np.float32).reshape(1, -1)

        reconstructed = self.quantizer.decode(self._codes)
        scores = reconstructed @ query_vec[0]
        top_k = np.argsort(-scores)[:top_k]

        return [self._documents[i] for i in top_k]

    def _merge_codes(self, existing, new):
        """Merge code dictionaries."""
        if isinstance(existing, dict) and isinstance(new, dict):
            merged = existing.copy()
            for key in merged:
                if key == "codes" and isinstance(merged[key], np.ndarray):
                    merged[key] = np.vstack([merged[key], new[key]])
            return merged
        return new

    def count_documents(self) -> int:
        """Count documents in the store."""
        return len(self._documents)

    def filter_documents(self, filters: Optional[Dict[str, Any]] = None) -> List[Document]:
        """Filter documents."""
        return self._documents
'''
    return code
