"""LangChain adapter generator."""

from typing import Dict, Any


def generate_langchain_adapter(quantizer_name: str, bit_width: int, dim: int) -> str:
    """Generate LangChain vector store adapter code.

    Args:
        quantizer_name: Name of the quantizer (turboquant, scalar, product).
        bit_width: Quantization bit width.
        dim: Vector dimensionality.

    Returns:
        Python code string for the adapter.
    """
    code = f'''"""
LangChain VectorStore adapter using {quantizer_name} quantization.

Auto-generated by QuantVec-CLI.
"""

from typing import List, Tuple, Optional
import numpy as np

try:
    from langchain_core.vectorstores import VectorStore
    from langchain_core.embeddings import Embeddings
       from langchain_core.documents import Document
except ImportError:
    raise ImportError("Please install langchain: pip install quantvec-cli[langchain]")

from quantvec.quantizers import {quantizer_name.title().replace("quant", "Quant")}Quantizer


class QuantVecStore(VectorStore):
    """A LangChain VectorStore that uses {quantizer_name} quantization."""

    def __init__(
        self,
        embedding: Embeddings,
        dim: int = {dim},
        bit_width: int = {bit_width},
    ):
        self.embedding = embedding
        self.dim = dim
        self.bit_width = bit_width
        self.quantizer = {quantizer_name.title().replace("quant", "Quant")}Quantizer(
            dim=dim, bit_width=bit_width
        )
        self._codes = None
        self._documents = []
        self._is_fitted = False

    def add_texts(
        self,
        texts: List[str],
        metadatas: Optional[List[dict]] = None,
        **kwargs: Any,
    ) -> List[str]:
        """Add texts to the store."""
        if metadatas is None:
            metadatas = [{{}}] * len(texts)

        # Embed
        vectors = self.embedding.embed_documents(texts)
        vectors = np.array(vectors, dtype=np.float32)

        # Fit quantizer on first batch if not fitted
        if not self._is_fitted:
            self.quantizer.fit(vectors)
            self._is_fitted = True

        # Encode
        codes = self.quantizer.encode(vectors)

        # Store
        if self._codes is None:
            self._codes = codes
        else:
            # Merge codes (implementation depends on quantizer type)
            self._codes = self._merge_codes(self._codes, codes)

        self._documents.extend([
            Document(page_content=t, metadata=m)
            for t, m in zip(texts, metadatas)
        ])

        return [str(i) for i in range(len(self._documents) - len(texts), len(self._documents))]

    def similarity_search(
        self, query: str, k: int = 4, **kwargs: Any
    ) -> List[Document]:
        """Search for similar documents."""
        query_vec = self.embedding.embed_query(query)
        query_vec = np.array(query_vec, dtype=np.float32).reshape(1, -1)

        # Decode all vectors
        reconstructed = self.quantizer.decode(self._codes)

        # Search
        scores = reconstructed @ query_vec[0]
        top_k = np.argsort(-scores)[:k]

        return [self._documents[i] for i in top_k]

    def _merge_codes(self, existing, new):
        """Merge two code dictionaries."""
        # Simplified merge for demonstration
        if isinstance(existing, dict) and isinstance(new, dict):
            merged = existing.copy()
            for key in merged:
                if key == "codes" and isinstance(merged[key], np.ndarray):
                    merged[key] = np.vstack([merged[key], new[key]])
            return merged
        return new

    @classmethod
    def from_texts(
        cls,
        texts: List[str],
        embedding: Embeddings,
        metadatas: Optional[List[dict]] = None,
        **kwargs: Any,
    ) -> "QuantVecStore":
        """Create store from texts."""
        store = cls(embedding=embedding, **kwargs)
        store.add_texts(texts, metadatas=metadatas)
        return store
'''
    return code
