"""LlamaIndex adapter generator."""

from typing import Dict, Any


def generate_llamaindex_adapter(quantizer_name: str, bit_width: int, dim: int) -> str:
    """Generate LlamaIndex vector store adapter code.

    Args:
        quantizer_name: Name of the quantizer.
        bit_width: Quantization bit width.
        dim: Vector dimensionality.

    Returns:
        Python code string for the adapter.
    """
    code = f'''"""
LlamaIndex VectorStore adapter using {quantizer_name} quantization.

Auto-generated by QuantVec-CLI.
"""

from typing import List, Optional, Any
import numpy as np

try:
    from llama_index.core.vector_stores.types import VectorStore, VectorStoreQuery, VectorStoreQueryResult
    from llama_index.core.schema import TextNode, BaseNode, NodeWithScore
except ImportError:
    raise ImportError("Please install llama-index: pip install quantvec-cli[llamaindex]")

from quantvec.quantizers import {quantizer_name.title().replace("quant", "Quant")}Quantizer


class QuantVecIndex(VectorStore):
    """A LlamaIndex VectorStore that uses {quantizer_name} quantization."""

    def __init__(
        self,
        dim: int = {dim},
        bit_width: int = {bit_width},
    ):
        self.dim = dim
        self.bit_width = bit_width
        self.quantizer = {quantizer_name.title().replace("quant", "Quant")}Quantizer(
            dim=dim, bit_width=bit_width
        )
        self._codes = None
        self._nodes = []
        self._is_fitted = False

    def add(self, nodes: List[BaseNode], **kwargs: Any) -> List[str]:
        """Add nodes to the index."""
        vectors = []
        for node in nodes:
            if node.embedding is None:
                raise ValueError("Node must have embedding")
            vectors.append(node.embedding)

        vectors = np.array(vectors, dtype=np.float32)

        if not self._is_fitted:
            self.quantizer.fit(vectors)
            self._is_fitted = True

        codes = self.quantizer.encode(vectors)

        if self._codes is None:
            self._codes = codes
        else:
            self._codes = self._merge_codes(self._codes, codes)

        self._nodes.extend(nodes)
        return [node.id_] for node in nodes]

    def query(self, query: VectorStoreQuery, **kwargs: Any) -> VectorStoreQueryResult:
        """Query the index."""
        query_vec = np.array(query.query_embedding, dtype=np.float32).reshape(1, -1)

        reconstructed = self.quantizer.decode(self._codes)
        scores = reconstructed @ query_vec[0]
        top_k = np.argsort(-scores)[:query.similarity_top_k]

        nodes_with_score = []
        for idx in top_k:
            node = self._nodes[idx]
            score = float(scores[idx])
            nodes_with_score.append(NodeWithScore(node=node, score=score))

        return VectorStoreQueryResult(nodes=nodes_with_score)

    def _merge_codes(self, existing, new):
        """Merge code dictionaries."""
        if isinstance(existing, dict) and isinstance(new, dict):
            merged = existing.copy()
            for key in merged:
                if key == "codes" and isinstance(merged[key], np.ndarray):
                    merged[key] = np.vstack([merged[key], new[key]])
            return merged
        return new

    @property
    def client(self) -> Any:
        """Return underlying client."""
        return self.quantizer
'''
    return code
